services:
  mariadb:
    image: mariadb:11.2.2
    restart: unless-stopped
    ports:
      - '3357:3306'
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_DATABASE: 'authorization'
      MARIADB_USER: 'authorization'
      MARIADB_PASSWORD: 'authorization'